// AUTO-GENERATED from cmpspec*.pas by generate_compiler_tables.py
// DO NOT EDIT MANUALLY

using System.Collections.Frozen;

namespace CoTAS.Compiler;

/// <summary>Complete command table - all ~140 TAS commands with options and defaults.</summary>
public static class CommandTable
{
    /// <summary>Lookup command by name (case-insensitive).</summary>
    public static readonly FrozenDictionary<string, CommandDef> Commands;

    /// <summary>All command definitions in declaration order.</summary>
    public static readonly CommandDef[] AllCommands;

    static CommandTable()
    {
        AllCommands = BuildAllCommands();
        var dict = new Dictionary<string, CommandDef>(StringComparer.OrdinalIgnoreCase);
        foreach (var cmd in AllCommands)
        {
            dict.TryAdd(cmd.Name, cmd); // first wins for duplicates like ? = PMSG
        }
        Commands = dict.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
    }

    private static CommandDef[] BuildAllCommands() =>
    [
        new() { Name = "*", Opcode = 0, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = ";", Opcode = 0, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "NOP", Opcode = 0, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "=", Opcode = 15, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(52, CompileAction.PE, 5)],
        },
        new() { Name = "->", Opcode = 18, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(53, CompileAction.CF, 5)],
        },
        new() { Name = "{", Opcode = 192, SpecSize = 4, IsSpecial = true,
        },
        new() { Name = "}", Opcode = 193, SpecSize = 0, IsSpecial = true,
        },
        new() { Name = "CLRSCR", Opcode = 2, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "CLR", Opcode = 6, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(49, CompileAction.CUfc, 5), new(50, CompileAction.CUfc, 5)],
            Defaults = [new(CompileAction.ChkChr, 5, "BR")],
        },
        new() { Name = "CLRLNE", Opcode = 7, SpecSize = 22, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(20, CompileAction.PF, 10), new(21, CompileAction.SetY, 15), new(6, CompileAction.PF, 16), new(174, CompileAction.SetY, 21)],
            Defaults = [new(CompileAction.ChkNy, 15), new(CompileAction.ChkNy, 21)],
        },
        new() { Name = "CLRSF", Opcode = 10, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "CLRPE", Opcode = 107, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "CURSOR", Opcode = 3, SpecSize = 13, Tas51SpecSize = 11, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 10), new(47, CompileAction.SetN, 10), new(13, CompileAction.CAt, 0), new(2, CompileAction.SetY, 11), new(41, CompileAction.SetY, 12)],
            Defaults = [new(CompileAction.ChkYn, 10), new(CompileAction.ChkNy, 11), new(CompileAction.ChkNy, 12)],
        },
        new() { Name = "BELL", Opcode = 4, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "CLOSE", Opcode = 8, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(51, CompileAction.SetY, 5)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "POSTMSG", Opcode = 11, SpecSize = 10, Tas51SpecSize = 38, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(275, CompileAction.PE, 5)],
        },
        new() { Name = "DEL", Opcode = 12, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(148, CompileAction.SetN, 5), new(11, CompileAction.LL, 6), new(22, CompileAction.ChkElbl, 11)],
            Defaults = [new(CompileAction.ChkYn, 5)],
        },
        new() { Name = "DALL", Opcode = 90, SpecSize = 37, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(27, CompileAction.CKey, 27), new(28, CompileAction.CFAll, 32), new(29, CompileAction.CScope, 21), new(30, CompileAction.PE, 5), new(31, CompileAction.PE, 10), new(74, CompileAction.CF, 16), new(32, CompileAction.SetY, 15)],
            Defaults = [new(CompileAction.ChkChr, 21, "ARNF")],
        },
        new() { Name = "ENTER", Opcode = 33, SpecSize = 97, Tas51SpecSize = 89, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 10), new(33, CompileAction.PE, 15), new(34, CompileAction.LUdf, 20), new(35, CompileAction.LL, 25), new(16, CompileAction.SetY, 36), new(36, CompileAction.SetY, 34), new(37, CompileAction.SetY, 35), new(1, CompileAction.CAt, 0), new(38, CompileAction.SetY, 64), new(6, CompileAction.PF, 37), new(39, CompileAction.PE, 42), new(40, CompileAction.PE, 47), new(41, CompileAction.PE, 54), new(42, CompileAction.PE, 29), new(267, CompileAction.PE, 29), new(43, CompileAction.PE, 59), new(44, CompileAction.PE, 65), new(173, CompileAction.CFAll, 74), new(15, CompileAction.SetY, 73), new(74, CompileAction.CF, 79), new(175, CompileAction.SetY, 84), new(215, CompileAction.PF, 85), new(222, CompileAction.SetY, 90), new(223, CompileAction.SetY, 91), new(240, CompileAction.PF, 92)],
            Defaults = [new(CompileAction.ChkNy, 73), new(CompileAction.ChkNy, 36), new(CompileAction.ChkNy, 34), new(CompileAction.ChkNy, 35), new(CompileAction.ChkNy, 64), new(CompileAction.ChkNy, 84), new(CompileAction.ChkNy, 90), new(CompileAction.ChkNy, 91)],
        },
        new() { Name = "FILL", Opcode = 17, SpecSize = 16, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(55, CompileAction.CUfc, 15), new(56, CompileAction.CUfc, 15), new(170, CompileAction.CUfc, 15), new(58, CompileAction.PE, 5), new(57, CompileAction.PF, 10)],
            Defaults = [new(CompileAction.ChkChr, 15, "LTA")],
        },
        new() { Name = "FIND", Opcode = 19, SpecSize = 33, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 15, "MGFLNPRES"), new(136, CompileAction.ChkFFld, 0), new(137, CompileAction.ChkRelFld, 10), new(22, CompileAction.ChkElbl, 16), new(103, CompileAction.SetY, 20), new(104, CompileAction.SetY, 21), new(30, CompileAction.PE, 22), new(31, CompileAction.PE, 27), new(107, CompileAction.SetY, 32)],
            Defaults = [new(CompileAction.ChkChr, 15, "MGFLNPRES"), new(CompileAction.ChkNy, 20), new(CompileAction.ChkNy, 21), new(CompileAction.ChkNy, 32)],
        },
        new() { Name = "GOSUB", Opcode = 21, SpecSize = 4, IsSpecial = false,
            Options = [new(0, CompileAction.LL, 0)],
        },
        new() { Name = "GOTO", Opcode = 22, SpecSize = 4, IsSpecial = false,
            Options = [new(0, CompileAction.LL, 0)],
        },
        new() { Name = "INIFLE", Opcode = 24, SpecSize = 11, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(113, CompileAction.PE, 6), new(26, CompileAction.SetY, 5)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "MENU", Opcode = 14, SpecSize = 89, Tas51SpecSize = 92, IsSpecial = false,
            Options = [new(117, CompileAction.CF, 60), new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(94, CompileAction.PF, 55), new(74, CompileAction.CF, 65), new(80, CompileAction.PF, 70), new(95, CompileAction.PF, 75), new(96, CompileAction.LL, 80), new(34, CompileAction.LL, 84), new(89, CompileAction.PE, 25), new(93, CompileAction.SetY, 88)],
            Defaults = [new(CompileAction.ChkChr1, 35, "S"), new(CompileAction.ChkChr1, 30, "L"), new(CompileAction.ChkNy, 88)],
        },
        new() { Name = "NMENU", Opcode = 27, SpecSize = 139, Tas51SpecSize = 124, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0), new(1, CompileAction.CAt, 5), new(77, CompileAction.PF, 90), new(78, CompileAction.PF, 20), new(79, CompileAction.CFAll, 15), new(74, CompileAction.CF, 50), new(80, CompileAction.PF, 25), new(81, CompileAction.PE, 30), new(15, CompileAction.SetY, 66), new(83, CompileAction.PE, 55), new(84, CompileAction.PF, 95), new(86, CompileAction.PF, 67), new(85, CompileAction.PF, 72), new(88, CompileAction.PE, 60), new(87, CompileAction.PF, 77), new(89, CompileAction.PE, 45), new(90, CompileAction.PE, 40), new(34, CompileAction.PE, 35), new(91, CompileAction.LL, 82), new(92, CompileAction.LL, 86), new(93, CompileAction.SetY, 65), new(130, CompileAction.SetY, 100), new(45, CompileAction.SetY, 101), new(176, CompileAction.PE, 102), new(200, CompileAction.SetY, 107), new(206, CompileAction.PF, 113), new(217, CompileAction.PF, 118), new(219, CompileAction.PF, 108), new(220, CompileAction.SetY, 123), new(225, CompileAction.CFAll, 124), new(226, CompileAction.PF, 129), new(235, CompileAction.PE, 134)],
            Defaults = [new(CompileAction.ChkNy, 66), new(CompileAction.ChkNy, 65), new(CompileAction.ChkNy, 100), new(CompileAction.ChkNy, 101), new(CompileAction.ChkNy, 107), new(CompileAction.ChkNy, 123)],
        },
        new() { Name = "MOUNT", Opcode = 28, SpecSize = 17, IsSpecial = true,
            Options = [new(0, CompileAction.GetScrnFormat, 0), new(7, CompileAction.ChkChr, 5, "SRB"), new(8, CompileAction.ChkChr, 6, "ASPDLX"), new(9, CompileAction.PE, 7), new(213, CompileAction.CF, 12)],
        },
        new() { Name = "ON", Opcode = 30, SpecSize = 0, IsSpecial = true,
            Options = [new(0, CompileAction.ParseOnGoto, 0)],
        },
        new() { Name = "OPEN", Opcode = 31, SpecSize = 54, Tas51SpecSize = 53, IsSpecial = false,
            Options = [new(0, CompileAction.CFile, 0), new(97, CompileAction.PE, 5), new(98, CompileAction.ChkChr, 10, "NRFAX"), new(22, CompileAction.ChkElbl, 11), new(100, CompileAction.PE, 15), new(101, CompileAction.PE, 20), new(102, CompileAction.PE, 25)],
            Defaults = [new(CompileAction.ChkChr, 10, "NRFAX"), new(CompileAction.ChkChr, 30, "T"), new(CompileAction.SetN, 53)],
        },
        new() { Name = "OPENV", Opcode = 64, SpecSize = 54, Tas51SpecSize = 53, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(105, CompileAction.CF, 31), new(97, CompileAction.PE, 5), new(98, CompileAction.ChkChr, 10, "NRFAXDO"), new(22, CompileAction.ChkElbl, 11), new(100, CompileAction.PE, 15), new(101, CompileAction.PE, 20), new(102, CompileAction.PE, 25), new(7, CompileAction.ChkChr, 30, "TXDFBC"), new(13, CompileAction.PF, 36), new(49, CompileAction.CF, 41), new(106, CompileAction.SetY, 46), new(107, CompileAction.SetY, 47), new(199, CompileAction.PE, 48), new(286, CompileAction.SetY, 53), new(305, CompileAction.SetY, 46)],
            Defaults = [new(CompileAction.ChkChr, 30, "TXDFB"), new(CompileAction.ChkChr, 10, "NRFAXDO"), new(CompileAction.ChkNy, 46), new(CompileAction.ChkNy, 47), new(CompileAction.ChkNy, 53)],
        },
        new() { Name = "ROPEN", Opcode = 131, SpecSize = 11, Tas51SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(199, CompileAction.PE, 5), new(286, CompileAction.SetY, 10)],
        },
        new() { Name = "MID", Opcode = 42, SpecSize = 26, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(28, CompileAction.PF, 5), new(20, CompileAction.PF, 10), new(117, CompileAction.PE, 15), new(66, CompileAction.SetN, 20), new(190, CompileAction.PF, 21)],
            Defaults = [new(CompileAction.ChkYn, 20)],
        },
        new() { Name = "REDEF", Opcode = 44, SpecSize = 50, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(7, CompileAction.PE, 5), new(13, CompileAction.PF, 10), new(14, CompileAction.PF, 15), new(60, CompileAction.CFile2, 20), new(61, CompileAction.PF, 25), new(27, CompileAction.PF, 30), new(19, CompileAction.PE, 35), new(82, CompileAction.CF, 40), new(16, CompileAction.PE, 45)],
        },
        new() { Name = "REDSP", Opcode = 45, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(150, CompileAction.SetY, 5)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "RET", Opcode = 32, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "SAVES", Opcode = 50, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(150, CompileAction.SetY, 5)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "SAVE", Opcode = 49, SpecSize = 16, Tas51SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(148, CompileAction.SetN, 6), new(107, CompileAction.SetN, 5), new(11, CompileAction.LL, 7), new(22, CompileAction.ChkElbl, 11), new(231, CompileAction.SetY, 15)],
            Defaults = [new(CompileAction.ChkYn, 6), new(CompileAction.ChkYn, 5), new(CompileAction.ChkNy, 15)],
        },
        new() { Name = "SCROLL", Opcode = 51, SpecSize = 26, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(72, CompileAction.PF, 20), new(16, CompileAction.CUfc, 25), new(124, CompileAction.CUfc, 25), new(125, CompileAction.CUfc, 25), new(126, CompileAction.CUfc, 25)],
            Defaults = [new(CompileAction.ChkChr, 25, "UDLR")],
        },
        new() { Name = "PTOF", Opcode = 53, SpecSize = 1, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 0, "DSP")],
            Defaults = [new(CompileAction.ChkChr, 0, "DSP")],
        },
        new() { Name = "TRAP", Opcode = 55, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.ChkTrap, 0), new(11, CompileAction.CTops, 5), new(12, CompileAction.CTops, 5), new(114, CompileAction.CTops, 5), new(41, CompileAction.CTops, 5), new(293, CompileAction.ChkChr1, 5, "F"), new(294, CompileAction.ChkChr1, 5, "F")],
            Defaults = [new(CompileAction.ChkChr, 5, "DSGI")],
        },
        new() { Name = "XTRAP", Opcode = 115, SpecSize = 7, IsSpecial = false,
            Options = [new(115, CompileAction.CUfc, 0), new(116, CompileAction.CUfc, 0), new(119, CompileAction.CUfc, 0), new(117, CompileAction.CF, 1), new(118, CompileAction.CUfc, 6), new(41, CompileAction.CUfc, 6), new(114, CompileAction.CUfc, 6)],
            Defaults = [new(CompileAction.ChkChr, 0, "SRC"), new(CompileAction.ChkChr, 6, "NDI")],
        },
        new() { Name = "ULKALL", Opcode = 56, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "WINDOW", Opcode = 57, SpecSize = 81, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(127, CompileAction.PF, 20), new(89, CompileAction.PE, 25), new(90, CompileAction.PE, 30), new(83, CompileAction.PE, 35), new(84, CompileAction.PF, 40), new(88, CompileAction.PE, 45), new(87, CompileAction.PF, 50), new(218, CompileAction.PF, 69), new(217, CompileAction.PF, 74), new(220, CompileAction.SetY, 79)],
            Defaults = [new(CompileAction.ChkNy, 79)],
        },
        new() { Name = "WINDEF", Opcode = 46, SpecSize = 81, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(127, CompileAction.PF, 20), new(89, CompileAction.PE, 25), new(90, CompileAction.PE, 30), new(83, CompileAction.PE, 35), new(84, CompileAction.PF, 40), new(88, CompileAction.PE, 45), new(87, CompileAction.PF, 50), new(171, CompileAction.PF, 55), new(128, CompileAction.CF, 60), new(218, CompileAction.CF, 69), new(217, CompileAction.CF, 74), new(220, CompileAction.SetY, 79)],
            Defaults = [new(CompileAction.ChkNy, 79)],
        },
        new() { Name = "WINACT", Opcode = 47, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0)],
        },
        new() { Name = "CHAIN", Opcode = 48, SpecSize = 21, Tas51SpecSize = 18, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(146, CompileAction.CFAllNoExp, 11), new(208, CompileAction.SetY, 16), new(299, CompileAction.SetY, 17), new(313, CompileAction.SetY, 18), new(314, CompileAction.SetY, 19)],
            Defaults = [new(CompileAction.ChkNy, 16)],
        },
        new() { Name = "EXEC", Opcode = 86, SpecSize = 15, Tas51SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(146, CompileAction.PF, 5)],
            Defaults = [new(CompileAction.ChkNy, 10)],
        },
        new() { Name = "SORTA", Opcode = 52, SpecSize = 21, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(72, CompileAction.PF, 5), new(73, CompileAction.CFAll, 10), new(74, CompileAction.CF, 15), new(75, CompileAction.CUfc, 20), new(76, CompileAction.CUfc, 20)],
            Defaults = [new(CompileAction.ChkChr, 20, "AD")],
        },
        new() { Name = "RDA", Opcode = 9, SpecSize = 47, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0), new(64, CompileAction.CFAllRfo, 5), new(60, CompileAction.CFile2, 10), new(27, CompileAction.CKey, 15), new(28, CompileAction.CFAll, 20), new(29, CompileAction.CScope, 25), new(30, CompileAction.PE, 31), new(31, CompileAction.PE, 36), new(74, CompileAction.CF, 41), new(32, CompileAction.SetY, 46)],
            Defaults = [new(CompileAction.ChkNy, 46), new(CompileAction.ChkChr, 25, "ARNF")],
        },
        new() { Name = "WRTA", Opcode = 13, SpecSize = 37, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0), new(64, CompileAction.CFAllRfo, 5), new(122, CompileAction.PF, 11), new(60, CompileAction.CFile2, 21), new(123, CompileAction.CF, 26), new(30, CompileAction.PE, 16), new(32, CompileAction.SetY, 31), new(74, CompileAction.CF, 32)],
            Defaults = [new(CompileAction.ChkNy, 31)],
        },
        new() { Name = "REMVA", Opcode = 65, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0)],
        },
        new() { Name = "DISPF", Opcode = 16, SpecSize = 31, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(61, CompileAction.PF, 5), new(1, CompileAction.CAt, 20), new(78, CompileAction.PF, 10), new(72, CompileAction.PF, 15), new(6, CompileAction.SetY, 30)],
            Defaults = [new(CompileAction.ChkNy, 30)],
        },
        new() { Name = "UPDTA", Opcode = 25, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.CFAllRfo, 0), new(66, CompileAction.CUfc, 5), new(51, CompileAction.CUfc, 5), new(68, CompileAction.CUfc, 5), new(69, CompileAction.CUfc, 5), new(70, CompileAction.CUfc, 5), new(278, CompileAction.CUfc, 5), new(57, CompileAction.PF, 6), new(71, CompileAction.PF, 11), new(246, CompileAction.PF, 11)],
            Defaults = [new(CompileAction.ChkChr, 5, "IDASC")],
        },
        new() { Name = "DEFINE", Opcode = 501, SpecSize = 0, IsSpecial = true,
            Options = [new(0, CompileAction.DefineFld, 0)],
        },
        new() { Name = "PMSG", Opcode = 1, SpecSize = 29, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 10), new(1, CompileAction.CAt, 0), new(2, CompileAction.SetY, 15), new(3, CompileAction.SetY, 16), new(4, CompileAction.ChkChr, 22, "DSP"), new(5, CompileAction.CF, 17), new(6, CompileAction.PF, 23), new(174, CompileAction.SetY, 28)],
            Defaults = [new(CompileAction.ChkNy, 15), new(CompileAction.ChkNy, 16), new(CompileAction.ChkNy, 28), new(CompileAction.ChkChr, 22, "DSP")],
        },
        new() { Name = "?", Opcode = 1, SpecSize = 29, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 10), new(1, CompileAction.CAt, 0), new(2, CompileAction.SetY, 15), new(3, CompileAction.SetY, 16), new(4, CompileAction.ChkChr, 22, "DSP"), new(5, CompileAction.CF, 17), new(6, CompileAction.PF, 23), new(174, CompileAction.SetY, 28)],
            Defaults = [new(CompileAction.ChkNy, 15), new(CompileAction.ChkNy, 16), new(CompileAction.ChkNy, 28), new(CompileAction.ChkChr, 22, "DSP")],
        },
        new() { Name = "PBLNK", Opcode = 34, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(4, CompileAction.ChkChr, 5, "DSP")],
            Defaults = [new(CompileAction.ChkChr, 5, "DSP")],
        },
        new() { Name = "PCHR", Opcode = 36, SpecSize = 11, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 1), new(4, CompileAction.ChkChr, 0, "DSP"), new(58, CompileAction.CFAll, 6)],
            Defaults = [new(CompileAction.ChkChr, 0, "DSP")],
        },
        new() { Name = "PFMT", Opcode = 37, SpecSize = 25, Tas51SpecSize = 24, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 12), new(144, CompileAction.PF, 18), new(1, CompileAction.CAt, 0), new(2, CompileAction.SetY, 10), new(3, CompileAction.SetY, 11), new(4, CompileAction.ChkChr, 17, "DSP"), new(174, CompileAction.SetY, 23), new(233, CompileAction.SetY, 24)],
            Defaults = [new(CompileAction.ChkNy, 10), new(CompileAction.ChkNy, 11), new(CompileAction.ChkNy, 23), new(CompileAction.ChkNy, 24), new(CompileAction.ChkChr, 17, "DSP")],
        },
        new() { Name = "PON", Opcode = 38, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 5, "ADSP"), new(9, CompileAction.PE, 0)],
            Defaults = [new(CompileAction.ChkChr, 5, "ADSP")],
        },
        new() { Name = "PVERT", Opcode = 40, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(4, CompileAction.ChkChr, 5, "DSP")],
            Defaults = [new(CompileAction.ChkChr, 5, "DSP")],
        },
        new() { Name = "PBOX", Opcode = 35, SpecSize = 33, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 20, "SDC"), new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(70, CompileAction.SetY, 21), new(278, CompileAction.SetY, 21), new(6, CompileAction.PF, 22), new(174, CompileAction.SetY, 32), new(167, CompileAction.PF, 27)],
            Defaults = [new(CompileAction.ChkNy, 21), new(CompileAction.ChkNy, 32), new(CompileAction.ChkChr, 20, "SDC")],
        },
        new() { Name = "IF", Opcode = 59, SpecSize = 20, IsSpecial = true,
            Options = [new(0, CompileAction.CompIf, 0)],
        },
        new() { Name = "ELSE", Opcode = 66, SpecSize = 4, IsSpecial = true,
            Options = [new(0, CompileAction.CompElse, 0)],
        },
        new() { Name = "ENDIF", Opcode = 502, SpecSize = 0, IsSpecial = true,
        },
        new() { Name = "ELSE_IF", Opcode = 503, SpecSize = 0, IsSpecial = true,
            Options = [new(0, CompileAction.CompElseIf, 0)],
        },
        new() { Name = "WHILE", Opcode = 67, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompWhile, 0)],
        },
        new() { Name = "ENDW", Opcode = 69, SpecSize = 5, IsSpecial = true,
            Options = [new(0, CompileAction.CompEndWhile, 0)],
        },
        new() { Name = "LOOP", Opcode = 504, SpecSize = 5, IsSpecial = true,
            Options = [new(0, CompileAction.CompWhileLoop, 0)],
        },
        new() { Name = "EXIT", Opcode = 508, SpecSize = 4, IsSpecial = true,
            Options = [new(0, CompileAction.CompWhileExit, 0)],
        },
        new() { Name = "LOOP_IF", Opcode = 70, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompWhileLoopIf, 0)],
        },
        new() { Name = "EXIT_IF", Opcode = 71, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompWhileExitIf, 0)],
        },
        new() { Name = "SELECT", Opcode = 68, SpecSize = 5, IsSpecial = true,
            Options = [new(0, CompileAction.CompSelect, 0)],
        },
        new() { Name = "CASE", Opcode = 147, SpecSize = 20, IsSpecial = true,
            Options = [new(0, CompileAction.CompCase, 0)],
        },
        new() { Name = "OTHERWISE", Opcode = 506, SpecSize = 4, IsSpecial = true,
            Options = [new(0, CompileAction.CompOtherwise, 0)],
        },
        new() { Name = "ENDC", Opcode = 507, SpecSize = 0, IsSpecial = true,
        },
        new() { Name = "FOR", Opcode = 72, SpecSize = 25, IsSpecial = true,
            Options = [new(0, CompileAction.CompFor, 0)],
        },
        new() { Name = "NEXT", Opcode = 220, SpecSize = 25, IsSpecial = true,
            Options = [new(0, CompileAction.CompNext, 0)],
        },
        new() { Name = "FLOOP", Opcode = 510, SpecSize = 5, IsSpecial = true,
            Options = [new(0, CompileAction.CompFloop, 0)],
        },
        new() { Name = "FEXIT", Opcode = 511, SpecSize = 4, IsSpecial = true,
            Options = [new(0, CompileAction.CompFexit, 0)],
        },
        new() { Name = "FLOOP_IF", Opcode = 512, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompFloopIf, 0)],
        },
        new() { Name = "FEXIT_IF", Opcode = 513, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompFexitIf, 0)],
        },
        new() { Name = "FUNC", Opcode = 73, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompUdf, 0)],
        },
        new() { Name = "CMD", Opcode = 74, SpecSize = 9, IsSpecial = true,
            Options = [new(0, CompileAction.CompUdc, 0)],
        },
        new() { Name = "POPS", Opcode = 60, SpecSize = 1, IsSpecial = false,
            Options = [new(114, CompileAction.SetY, 0)],
        },
        new() { Name = "RAP", Opcode = 76, SpecSize = 21, Tas51SpecSize = 17, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(72, CompileAction.PF, 5), new(146, CompileAction.CFAll, 11)],
        },
        new() { Name = "CHAINR", Opcode = 77, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "REPL", Opcode = 85, SpecSize = 53, IsSpecial = false,
            Options = [new(0, CompileAction.CFAllRfo, 5), new(146, CompileAction.CFAll, 0), new(60, CompileAction.CFile2, 10), new(27, CompileAction.CKey, 15), new(28, CompileAction.CFAll, 20), new(29, CompileAction.CScope, 25), new(30, CompileAction.PE, 31), new(31, CompileAction.PE, 36), new(74, CompileAction.CF, 41), new(72, CompileAction.PF, 46), new(120, CompileAction.SetY, 51), new(32, CompileAction.SetY, 52)],
            Defaults = [new(CompileAction.ChkNy, 51), new(CompileAction.ChkNy, 52), new(CompileAction.ChkChr, 25, "ARNF")],
        },
        new() { Name = "QUIT", Opcode = 87, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "ERR", Opcode = 88, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(72, CompileAction.PF, 5)],
        },
        new() { Name = "OWNER", Opcode = 89, SpecSize = 13, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 6), new(60, CompileAction.CFile2, 0), new(70, CompileAction.CUfc, 5), new(278, CompileAction.CUfc, 5), new(110, CompileAction.CUfc, 5), new(111, CompileAction.SetY, 11), new(112, CompileAction.SetY, 12)],
            Defaults = [new(CompileAction.ChkChr, 5, "CS"), new(CompileAction.ChkNy, 11), new(CompileAction.ChkNy, 12)],
        },
        new() { Name = "ASK", Opcode = 91, SpecSize = 30, Tas51SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(41, CompileAction.PE, 5), new(209, CompileAction.PE, 10), new(306, CompileAction.PE, 15), new(309, CompileAction.PE, 20), new(310, CompileAction.PE, 25)],
        },
        new() { Name = "REL", Opcode = 93, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(27, CompileAction.CKey, 5), new(63, CompileAction.CFile2, 10), new(135, CompileAction.CFAll, 15)],
        },
        new() { Name = "ADD", Opcode = 82, SpecSize = 55, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(7, CompileAction.PE, 5), new(13, CompileAction.PF, 10), new(14, CompileAction.PF, 15), new(15, CompileAction.PF, 45), new(16, CompileAction.PE, 20), new(19, CompileAction.PE, 25), new(60, CompileAction.CFile2, 30), new(61, CompileAction.PF, 35), new(27, CompileAction.PF, 50), new(62, CompileAction.CF, 40)],
        },
        new() { Name = "PAINT", Opcode = 96, SpecSize = 25, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 20), new(65, CompileAction.CAt, 0), new(144, CompileAction.CAt, 10)],
        },
        new() { Name = "XFER", Opcode = 29, SpecSize = 26, Tas51SpecSize = 25, IsSpecial = false,
            Options = [new(65, CompileAction.CF, 0), new(64, CompileAction.CF, 5), new(20, CompileAction.PF, 10), new(152, CompileAction.PF, 15), new(154, CompileAction.PF, 20), new(304, CompileAction.SetY, 25)],
        },
        new() { Name = "TRANSX", Opcode = 54, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 0, "BCR"), new(22, CompileAction.CF, 1)],
            Defaults = [new(CompileAction.ChkChr, 0, "BCR")],
        },
        new() { Name = "DEALOC", Opcode = 97, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0)],
        },
        new() { Name = "READ", Opcode = 98, SpecSize = 30, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(28, CompileAction.PF, 5), new(20, CompileAction.PF, 10), new(64, CompileAction.CF, 15), new(190, CompileAction.PF, 20), new(61, CompileAction.PF, 25)],
        },
        new() { Name = "WRITE", Opcode = 99, SpecSize = 30, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(28, CompileAction.PF, 5), new(20, CompileAction.PF, 10), new(65, CompileAction.CF, 15), new(190, CompileAction.PF, 20), new(61, CompileAction.PF, 25)],
        },
        new() { Name = "INSERT", Opcode = 100, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 5), new(67, CompileAction.CF, 0)],
        },
        new() { Name = "REMOUNT", Opcode = 102, SpecSize = 5, IsSpecial = true,
            Options = [new(0, CompileAction.GetScrnFormat, 0)],
        },
        new() { Name = "SCRN", Opcode = 103, SpecSize = 1, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 0, "SRLUED")],
            Defaults = [new(CompileAction.ChkChr, 0, "SRLUED")],
        },
        new() { Name = "MSG", Opcode = 106, SpecSize = 20, Tas51SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(45, CompileAction.ChkChr1, 5, "N"), new(216, CompileAction.PF, 10), new(209, CompileAction.PE, 15), new(308, CompileAction.ChkChr1, 6, "N")],
            Defaults = [],
        },
        new() { Name = "UPAR", Opcode = 108, SpecSize = 9, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(11, CompileAction.LL, 5)],
        },
        new() { Name = "ALLOC", Opcode = 109, SpecSize = 35, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(7, CompileAction.PE, 5), new(13, CompileAction.PF, 10), new(14, CompileAction.PF, 15), new(15, CompileAction.PF, 20), new(16, CompileAction.PE, 25), new(33, CompileAction.PE, 30)],
        },
        new() { Name = "IMPORT", Opcode = 112, SpecSize = 63, IsSpecial = false,
            Options = [new(0, CompileAction.CFAllRfo, 0), new(64, CompileAction.CFile2, 10), new(7, CompileAction.PE, 53), new(29, CompileAction.CScope, 25), new(30, CompileAction.PE, 31), new(65, CompileAction.PE, 5), new(120, CompileAction.SetY, 51), new(122, CompileAction.PF, 46), new(74, CompileAction.CF, 41), new(156, CompileAction.PE, 58), new(32, CompileAction.SetY, 52)],
            Defaults = [new(CompileAction.ChkNy, 51), new(CompileAction.ChkNy, 52), new(CompileAction.ChkChr, 25, "ARNF")],
        },
        new() { Name = "EXPORT", Opcode = 80, SpecSize = 74, Tas51SpecSize = 68, IsSpecial = false,
            Options = [new(60, CompileAction.CFile2, 10), new(27, CompileAction.CKey, 15), new(28, CompileAction.CFAll, 20), new(29, CompileAction.CScope, 25), new(30, CompileAction.PE, 31), new(31, CompileAction.PE, 36), new(74, CompileAction.CF, 41), new(72, CompileAction.PF, 46), new(120, CompileAction.SetY, 51), new(32, CompileAction.SetY, 52), new(64, CompileAction.PE, 5), new(7, CompileAction.PE, 53), new(156, CompileAction.PE, 58), new(157, CompileAction.PE, 63), new(262, CompileAction.PE, 65), new(317, CompileAction.PE, 66)],
            Defaults = [new(CompileAction.ChkNy, 51), new(CompileAction.ChkNy, 52), new(CompileAction.ChkChr, 25, "ARNF")],
        },
        new() { Name = "PARAM", Opcode = 113, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CFAllRfo, 0)],
        },
        new() { Name = "DELC", Opcode = 123, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(28, CompileAction.PF, 5), new(20, CompileAction.PF, 10), new(190, CompileAction.PF, 15)],
        },
        new() { Name = "GOTOL", Opcode = 124, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "REENT", Opcode = 58, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "FORCE", Opcode = 94, SpecSize = 1, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 0), new(47, CompileAction.SetN, 0)],
            Defaults = [new(CompileAction.ChkNy, 0)],
        },
        new() { Name = "PSET", Opcode = 110, SpecSize = 35, Tas51SpecSize = 20, IsSpecial = false,
            Options = [new(78, CompileAction.PF, 0), new(158, CompileAction.PF, 5), new(159, CompileAction.PF, 10), new(181, CompileAction.PE, 15), new(232, CompileAction.PE, 20), new(230, CompileAction.PF, 25), new(233, CompileAction.PF, 30)],
        },
        new() { Name = "COLOR", Opcode = 111, SpecSize = 30, IsSpecial = false,
            Options = [new(160, CompileAction.PF, 0), new(161, CompileAction.PF, 5), new(162, CompileAction.PF, 10), new(22, CompileAction.PF, 15), new(5, CompileAction.PF, 20), new(15, CompileAction.CF, 25)],
        },
        new() { Name = "SETACT", Opcode = 116, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CSchema, 0), new(60, CompileAction.CFile, 5)],
        },
        new() { Name = "BKG", Opcode = 117, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "FRG", Opcode = 118, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "REV", Opcode = 119, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "DELF", Opcode = 125, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "RENF", Opcode = 126, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(64, CompileAction.PE, 5)],
        },
        new() { Name = "CO", Opcode = 43, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(109, CompileAction.CUfc, 5), new(110, CompileAction.CUfc, 5)],
            Defaults = [new(CompileAction.ChkChr, 5, "GS")],
        },
        new() { Name = "DATE", Opcode = 127, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(109, CompileAction.CUfc, 5), new(110, CompileAction.CUfc, 5)],
            Defaults = [new(CompileAction.ChkChr, 5, "GS")],
        },
        new() { Name = "FORMAT", Opcode = 120, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(59, CompileAction.CF, 5), new(163, CompileAction.SetN, 10), new(164, CompileAction.SetN, 11), new(165, CompileAction.ChkChr, 12, "LTPCA"), new(47, CompileAction.SetY, 13), new(19, CompileAction.PE, 14), new(182, CompileAction.SetY, 19)],
            Defaults = [new(CompileAction.ChkYn, 10), new(CompileAction.ChkYn, 11), new(CompileAction.ChkNy, 13), new(CompileAction.ChkNy, 19), new(CompileAction.ChkChr, 12, "LTPCA")],
        },
        new() { Name = "SCRCHR", Opcode = 69, SpecSize = 21, Tas51SpecSize = 5, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(32, CompileAction.CF, 10), new(99, CompileAction.CF, 15), new(203, CompileAction.CF, 21), new(109, CompileAction.CUfc, 20), new(110, CompileAction.CUfc, 20)],
            Defaults = [new(CompileAction.ChkChr, 20, "GS")],
        },
        new() { Name = "TIME", Opcode = 128, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(109, CompileAction.CUfc, 5), new(110, CompileAction.CUfc, 5)],
            Defaults = [new(CompileAction.ChkChr, 5, "GS")],
        },
        new() { Name = "FINDV", Opcode = 26, SpecSize = 33, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChrFt, 15, "MGFLNPRES"), new(105, CompileAction.PF, 0), new(27, CompileAction.CKey, 5), new(71, CompileAction.CFAll, 10), new(246, CompileAction.CFAll, 10), new(22, CompileAction.ChkElbl, 16), new(103, CompileAction.SetY, 20), new(104, CompileAction.SetY, 21), new(30, CompileAction.PE, 22), new(31, CompileAction.PE, 27), new(107, CompileAction.SetY, 32)],
            Defaults = [new(CompileAction.ChkChrFt, 15, "MGFLNPRES"), new(CompileAction.ChkNy, 20), new(CompileAction.ChkNy, 21), new(CompileAction.ChkNy, 32)],
        },
        new() { Name = "BRKRET", Opcode = 39, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "SRCH", Opcode = 20, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(27, CompileAction.CKey, 5)],
        },
        new() { Name = "LISTM", Opcode = 79, SpecSize = 126, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0), new(5, CompileAction.PE, 58), new(136, CompileAction.PE, 27), new(34, CompileAction.LUdf, 69), new(138, CompileAction.PE, 15), new(133, CompileAction.PE, 22), new(142, CompileAction.SetY, 20), new(143, CompileAction.PF, 10), new(74, CompileAction.CF, 5), new(45, CompileAction.SetY, 57), new(122, CompileAction.PF, 64), new(141, CompileAction.SetY, 21), new(139, CompileAction.SetY, 63), new(85, CompileAction.PF, 74), new(16, CompileAction.SetY, 79), new(176, CompileAction.PE, 80), new(180, CompileAction.PE, 85), new(183, CompileAction.SetY, 90), new(184, CompileAction.CFAll, 91), new(185, CompileAction.PE, 96), new(186, CompileAction.PF, 101), new(187, CompileAction.SetY, 106), new(193, CompileAction.PF, 107), new(200, CompileAction.SetY, 112), new(201, CompileAction.SetY, 113), new(202, CompileAction.SetY, 114), new(205, CompileAction.PF, 120), new(206, CompileAction.PF, 115), new(220, CompileAction.SetY, 125)],
            Defaults = [new(CompileAction.ChkNy, 20), new(CompileAction.ChkNy, 21), new(CompileAction.ChkNy, 57), new(CompileAction.ChkNy, 63), new(CompileAction.ChkNy, 79), new(CompileAction.ChkNy, 90), new(CompileAction.ChkNy, 106), new(CompileAction.ChkNy, 112), new(CompileAction.ChkNy, 113), new(CompileAction.ChkNy, 114), new(CompileAction.ChkNy, 125)],
        },
        new() { Name = "LISTF", Opcode = 83, SpecSize = 126, Tas51SpecSize = 125, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0), new(5, CompileAction.PE, 58), new(136, CompileAction.PE, 27), new(34, CompileAction.PE, 69), new(138, CompileAction.PE, 15), new(133, CompileAction.PE, 22), new(60, CompileAction.CFile2, 32), new(27, CompileAction.CKey, 37), new(28, CompileAction.CFAll, 52), new(30, CompileAction.PE, 42), new(31, CompileAction.PE, 47), new(142, CompileAction.SetY, 20), new(45, CompileAction.SetY, 57), new(141, CompileAction.SetY, 21), new(139, CompileAction.SetY, 63), new(85, CompileAction.PF, 74), new(16, CompileAction.SetY, 79), new(176, CompileAction.PE, 80), new(180, CompileAction.PE, 85), new(183, CompileAction.SetY, 90), new(184, CompileAction.CFAll, 91), new(185, CompileAction.PE, 96), new(186, CompileAction.PF, 101), new(187, CompileAction.SetY, 106), new(193, CompileAction.PF, 107), new(200, CompileAction.SetY, 112), new(201, CompileAction.SetY, 113), new(202, CompileAction.SetY, 114), new(205, CompileAction.PF, 120), new(206, CompileAction.PF, 115), new(220, CompileAction.SetY, 125)],
            Defaults = [new(CompileAction.ChkNy, 20), new(CompileAction.ChkNy, 21), new(CompileAction.ChkNy, 57), new(CompileAction.ChkNy, 63), new(CompileAction.ChkNy, 79), new(CompileAction.ChkNy, 90), new(CompileAction.ChkNy, 106), new(CompileAction.ChkNy, 112), new(CompileAction.ChkNy, 113), new(CompileAction.ChkNy, 114)],
        },
        new() { Name = "RCN", Opcode = 92, SpecSize = 12, IsSpecial = false,
            Options = [new(0, CompileAction.CFile2, 0), new(108, CompileAction.CF, 5), new(109, CompileAction.CUfc, 10), new(110, CompileAction.CUfc, 10), new(103, CompileAction.SetY, 11)],
            Defaults = [new(CompileAction.ChkChr, 10, "GS"), new(CompileAction.ChkNy, 11)],
        },
        new() { Name = "LIST", Opcode = 84, SpecSize = 59, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0), new(89, CompileAction.CFAll, 5), new(60, CompileAction.CFile2, 10), new(27, CompileAction.CKey, 15), new(28, CompileAction.CFAll, 20), new(29, CompileAction.CScope, 25), new(30, CompileAction.PE, 31), new(31, CompileAction.PE, 36), new(74, CompileAction.CF, 41), new(72, CompileAction.PF, 46), new(120, CompileAction.SetY, 51), new(8, CompileAction.ChkChr, 52, "ADSP"), new(9, CompileAction.PE, 53), new(151, CompileAction.SetY, 58)],
            Defaults = [new(CompileAction.ChkNy, 51), new(CompileAction.ChkNy, 58), new(CompileAction.ChkChr, 25, "ARNF"), new(CompileAction.ChkChr, 52, "ADSP")],
        },
        new() { Name = "RSCR", Opcode = 81, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "SAY", Opcode = 23, SpecSize = 25, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(1, CompileAction.CAt, 5), new(6, CompileAction.PF, 15), new(19, CompileAction.PE, 20)],
        },
        new() { Name = "FILTER", Opcode = 132, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "WRAP", Opcode = 133, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(166, CompileAction.PF, 5), new(169, CompileAction.PF, 10)],
        },
        new() { Name = "REWRAP", Opcode = 134, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "INC", Opcode = 41, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0)],
        },
        new() { Name = "DEC", Opcode = 95, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0)],
        },
        new() { Name = "UP", Opcode = 135, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(170, CompileAction.SetY, 5)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "SCAN", Opcode = 137, SpecSize = 43, IsSpecial = true,
            Options = [new(0, CompileAction.CFile2, 4), new(27, CompileAction.CKey, 9), new(28, CompileAction.CFAll, 14), new(29, CompileAction.CScope, 19), new(30, CompileAction.PE, 25), new(31, CompileAction.PE, 30), new(32, CompileAction.SetY, 35), new(103, CompileAction.SetY, 36), new(162, CompileAction.SetY, 42)],
            Defaults = [new(CompileAction.ChkNy, 35), new(CompileAction.ChkNy, 36), new(CompileAction.ChkNy, 42), new(CompileAction.ChkChr, 19, "ARNF")],
        },
        new() { Name = "SEXIT", Opcode = 514, SpecSize = 4, IsSpecial = true,
        },
        new() { Name = "SEXIT_IF", Opcode = 515, SpecSize = 9, IsSpecial = true,
        },
        new() { Name = "SLOOP", Opcode = 516, SpecSize = 9, IsSpecial = true,
        },
        new() { Name = "SLOOP_IF", Opcode = 517, SpecSize = 9, IsSpecial = true,
        },
        new() { Name = "ENDS", Opcode = 518, SpecSize = 9, IsSpecial = true,
        },
        new() { Name = "TRIM", Opcode = 139, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(55, CompileAction.CUfc, 5), new(56, CompileAction.CUfc, 5)],
            Defaults = [new(CompileAction.ChkChr, 5, "TL")],
        },
        new() { Name = "IFDUP", Opcode = 140, SpecSize = 20, IsSpecial = true,
            Options = [new(0, CompileAction.CompIfdup, 0)],
        },
        new() { Name = "IFNA", Opcode = 141, SpecSize = 20, IsSpecial = true,
            Options = [new(0, CompileAction.CompIfna, 0)],
        },
        new() { Name = "CLOCK", Opcode = 136, SpecSize = 12, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 0), new(47, CompileAction.SetN, 0), new(1, CompileAction.CAt, 1), new(121, CompileAction.SetY, 11)],
            Defaults = [new(CompileAction.ChkYn, 0), new(CompileAction.ChkNy, 11)],
        },
        new() { Name = "PRTALL", Opcode = 142, SpecSize = 1, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 0), new(47, CompileAction.SetN, 0)],
            Defaults = [new(CompileAction.ChkNy, 0)],
        },
        new() { Name = "NOREDSP", Opcode = 143, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "RDLIST", Opcode = 104, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "AUTOINC", Opcode = 144, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "AUTODEC", Opcode = 163, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "LIST_EXIT", Opcode = 156, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "PUSHT", Opcode = 145, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.ChkTrap, 0)],
        },
        new() { Name = "POPT", Opcode = 146, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.ChkTrap, 0)],
        },
        new() { Name = "CLSPF", Opcode = 78, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "PUSHF", Opcode = 129, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CFAllRfo, 0)],
        },
        new() { Name = "POPF", Opcode = 130, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CFAllRfo, 0)],
        },
        new() { Name = "PRT_NUM", Opcode = 148, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "LD_PDRV", Opcode = 149, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "GOSUBL", Opcode = 150, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "GETLBL", Opcode = 151, SpecSize = 9, IsSpecial = false,
            Options = [new(0, CompileAction.LL, 0), new(117, CompileAction.CF, 4)],
        },
        new() { Name = "CDPATH", Opcode = 152, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "SOUND", Opcode = 153, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(177, CompileAction.CF, 5), new(72, CompileAction.PF, 10), new(60, CompileAction.PF, 15)],
        },
        new() { Name = "TRACE", Opcode = 154, SpecSize = 11, IsSpecial = false,
            Options = [new(28, CompileAction.Cc1PE, 0, "S"), new(291, CompileAction.Cc1PE, 0, "W"), new(48, CompileAction.ChkChr1, 0, "X"), new(157, CompileAction.SetY, 10)],
        },
        new() { Name = "INT", Opcode = 155, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(179, CompileAction.PE, 5)],
        },
        new() { Name = "PEEK", Opcode = 158, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(117, CompileAction.CF, 5), new(20, CompileAction.PF, 10)],
        },
        new() { Name = "POKE", Opcode = 157, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(117, CompileAction.CF, 5), new(20, CompileAction.PF, 10)],
        },
        new() { Name = "KBDUP", Opcode = 159, SpecSize = 1, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 0), new(47, CompileAction.SetN, 0)],
            Defaults = [new(CompileAction.ChkYn, 0)],
        },
        new() { Name = "NORSTRT", Opcode = 160, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "NOVLDMSG", Opcode = 161, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "SETLINE", Opcode = 101, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(146, CompileAction.CFAll, 5)],
        },
        new() { Name = "AUTOENTER", Opcode = 162, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "SHOW_PLINE", Opcode = 164, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CAt, 0)],
        },
        new() { Name = "AUTO_RUN", Opcode = 165, SpecSize = 11, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(188, CompileAction.PF, 5), new(189, CompileAction.SetY, 10)],
            Defaults = [new(CompileAction.ChkNy, 10)],
        },
        new() { Name = "RUN", Opcode = 166, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "DISPM", Opcode = 121, SpecSize = 40, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(28, CompileAction.PF, 5), new(192, CompileAction.PF, 10), new(61, CompileAction.PF, 15), new(1, CompileAction.CAt, 20), new(78, CompileAction.PF, 30), new(191, CompileAction.PF, 35)],
        },
        new() { Name = "FILLMEM", Opcode = 122, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(28, CompileAction.PF, 5), new(20, CompileAction.PF, 10), new(58, CompileAction.PE, 15)],
        },
        new() { Name = "PUT_FLD", Opcode = 62, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0)],
        },
        new() { Name = "MEM_PTR", Opcode = 167, SpecSize = 35, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(28, CompileAction.PF, 5), new(13, CompileAction.PF, 10), new(71, CompileAction.PF, 15), new(246, CompileAction.PF, 15), new(192, CompileAction.PF, 20), new(57, CompileAction.PF, 25), new(44, CompileAction.PE, 30)],
        },
        new() { Name = "MEM_SPC", Opcode = 168, SpecSize = 25, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(28, CompileAction.PF, 5), new(48, CompileAction.PF, 10), new(20, CompileAction.PF, 15), new(44, CompileAction.PE, 20)],
        },
        new() { Name = "SAVES3", Opcode = 169, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "REDSP3", Opcode = 170, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "SSPCF", Opcode = 172, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "SORT3", Opcode = 63, SpecSize = 25, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(117, CompileAction.CF, 5), new(13, CompileAction.PF, 10), new(72, CompileAction.PF, 15), new(44, CompileAction.PF, 20)],
        },
        new() { Name = "WRAP3", Opcode = 171, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0)],
        },
        new() { Name = "RDREC", Opcode = 173, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.ChkElbl, 0)],
        },
        new() { Name = "WTREC", Opcode = 174, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.ChkElbl, 0)],
        },
        new() { Name = "CLSO", Opcode = 61, SpecSize = 1, IsSpecial = false,
            Options = [new(0, CompileAction.ChkChr, 0, "NY")],
            Defaults = [new(CompileAction.ChkNy, 0)],
        },
        new() { Name = "OPNO", Opcode = 175, SpecSize = 48, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(7, CompileAction.ChkChr, 30, "XF"), new(13, CompileAction.PF, 36), new(49, CompileAction.CF, 41)],
            Defaults = [new(CompileAction.ChkChr, 30, "XF")],
        },
        new() { Name = "EQU_MID", Opcode = 176, SpecSize = 25, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(117, CompileAction.CF, 5), new(28, CompileAction.PF, 10), new(20, CompileAction.PF, 15), new(190, CompileAction.PF, 20)],
        },
        new() { Name = "EQU_DAY", Opcode = 177, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(117, CompileAction.PF, 5)],
        },
        new() { Name = "EQU_XMT", Opcode = 178, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(117, CompileAction.PF, 5)],
        },
        new() { Name = "FORCE3", Opcode = 179, SpecSize = 1, IsSpecial = false,
            Options = [new(0, CompileAction.ChkNy, 0)],
            Defaults = [new(CompileAction.ChkNy, 0)],
        },
        new() { Name = "MOUSE", Opcode = 180, SpecSize = 31, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 30), new(47, CompileAction.SetN, 30)],
            Defaults = [new(CompileAction.ChkYn, 30)],
        },
        new() { Name = "PLAYWAV", Opcode = 181, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "COMM", Opcode = 182, SpecSize = 0, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "JUST", Opcode = 183, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.CF, 0), new(125, CompileAction.CUfc, 5), new(126, CompileAction.CUfc, 5), new(196, CompileAction.CUfc, 5)],
            Defaults = [new(CompileAction.ChkChr, 5, "CRL")],
        },
        new() { Name = "PORT", Opcode = 184, SpecSize = 11, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(117, CompileAction.CF, 5), new(197, CompileAction.CUfc, 10), new(198, CompileAction.CUfc, 10)],
            Defaults = [new(CompileAction.ChkChr, 10, "IO")],
        },
        new() { Name = "AUTONEW", Opcode = 186, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "WCOLOR", Opcode = 187, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PF, 0), new(71, CompileAction.PF, 5), new(246, CompileAction.PF, 5)],
        },
        new() { Name = "BUTTON", Opcode = 188, SpecSize = 58, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(6, CompileAction.PF, 20), new(203, CompileAction.PF, 30), new(209, CompileAction.PE, 25), new(27, CompileAction.PE, 35), new(213, CompileAction.CF, 41), new(214, CompileAction.CF, 46), new(221, CompileAction.CF, 53), new(210, CompileAction.SetY, 40), new(46, CompileAction.SetY, 52), new(47, CompileAction.SetY, 51)],
            Defaults = [new(CompileAction.ChkNy, 40), new(CompileAction.ChkNy, 51), new(CompileAction.ChkNy, 52)],
        },
        new() { Name = "CAPTION", Opcode = 189, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(207, CompileAction.SetY, 5)],
            Defaults = [new(CompileAction.ChkNy, 5)],
        },
        new() { Name = "LOAD_PICTURE", Opcode = 190, SpecSize = 15, Tas51SpecSize = 39, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(60, CompileAction.PE, 5), new(117, CompileAction.CF, 10), new(290, CompileAction.CF, 10)],
        },
        new() { Name = "GRAY", Opcode = 191, SpecSize = 1, IsSpecial = false,
            Options = [new(46, CompileAction.SetY, 0), new(47, CompileAction.SetN, 0)],
            Defaults = [new(CompileAction.ChkNy, 0)],
        },
        new() { Name = "ROW_COLOR", Opcode = 194, SpecSize = 20, IsSpecial = false,
            Options = [new(65, CompileAction.PF, 0), new(144, CompileAction.PF, 5), new(6, CompileAction.PF, 10), new(203, CompileAction.PF, 15)],
        },
        new() { Name = "CLIK_SRCH_LIMIT", Opcode = 195, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "HOT_SPOT", Opcode = 196, SpecSize = 31, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(27, CompileAction.PE, 25), new(72, CompileAction.CF, 20), new(210, CompileAction.SetY, 30)],
            Defaults = [new(CompileAction.ChkNy, 30)],
        },
        new() { Name = "WMENU", Opcode = 197, SpecSize = 41, IsSpecial = false,
        },
        new() { Name = "WMENU", Opcode = 197, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(1, CompileAction.CAt, 5)],
        },
        new() { Name = "WHELP", Opcode = 198, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(289, CompileAction.PF, 5)],
        },
        new() { Name = "REGIONSOFF", Opcode = 200, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0)],
        },
        new() { Name = "REFRESHFORM", Opcode = 200, SpecSize = 0, IsSpecial = false,
        },
        new() { Name = "INIT_REGION*", Opcode = 201, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.CFAll, 0)],
        },
        new() { Name = "MARK_REGION*", Opcode = 202, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(230, CompileAction.PF, 5)],
        },
        new() { Name = "NO_PRINT_FLD*", Opcode = 203, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "SETUP_REPORT_BUFF", Opcode = 204, SpecSize = 15, IsSpecial = false,
            Options = [new(236, CompileAction.PF, 0), new(298, CompileAction.PE, 5), new(237, CompileAction.PF, 10)],
        },
        new() { Name = "OUTPUT_REPORT_DATA", Opcode = 205, SpecSize = 16, IsSpecial = false,
            Options = [new(236, CompileAction.PF, 0)],
            Defaults = [new(CompileAction.ChkNy, 15)],
        },
        new() { Name = "UPDATE_REPORT_DATA", Opcode = 206, SpecSize = 10, IsSpecial = false,
            Options = [new(236, CompileAction.PF, 0), new(135, CompileAction.CFAll, 5)],
        },
        new() { Name = "PRINT_PROGRESS", Opcode = 207, SpecSize = 21, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(78, CompileAction.PF, 10), new(311, CompileAction.PF, 15), new(47, CompileAction.SetY, 20)],
            Defaults = [new(CompileAction.SetN, 20)],
        },
        new() { Name = "WMOUNT", Opcode = 208, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "SET_FOCUS", Opcode = 209, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "SET_OBJECT", Opcode = 210, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(247, CompileAction.PE, 5), new(246, CompileAction.PE, 10), new(275, CompileAction.PF, 15)],
        },
        new() { Name = "COMBO_ITEM", Opcode = 211, SpecSize = 16, IsSpecial = false,
            Options = [new(262, CompileAction.PE, 0), new(266, CompileAction.PE, 5), new(69, CompileAction.CCaVal, 10), new(70, CompileAction.CCaVal, 10), new(278, CompileAction.CCaVal, 10), new(307, CompileAction.CCaVal, 10)],
        },
        new() { Name = "NAVIGATOR", Opcode = 212, SpecSize = 15, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(105, CompileAction.PF, 5), new(27, CompileAction.CKey, 10), new(103, CompileAction.SetY, 15)],
            Defaults = [new(CompileAction.ChkYn, 15)],
        },
        new() { Name = "WLISTF", Opcode = 213, SpecSize = 57, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(34, CompileAction.PE, 10), new(105, CompileAction.PF, 15), new(27, CompileAction.CKey, 20), new(28, CompileAction.CFAll, 25), new(30, CompileAction.PE, 30), new(31, CompileAction.PE, 35), new(249, CompileAction.CUfc, 42), new(253, CompileAction.CUfc, 42), new(264, CompileAction.ChkChr1, 42, "F"), new(274, CompileAction.CUfc, 42), new(288, CompileAction.ChkChr1, 42, "U"), new(252, CompileAction.ChkChr1, 43, "R"), new(258, CompileAction.ChkChr1, 43, "T"), new(260, CompileAction.ChkChr1, 43, "E"), new(254, CompileAction.CUfc, 43), new(265, CompileAction.ChkChr1, 43, "C"), new(272, CompileAction.ChkChr1, 43, "A"), new(262, CompileAction.PE, 5), new(16, CompileAction.SetY, 44), new(64, CompileAction.PF, 50), new(268, CompileAction.SetY, 55), new(269, CompileAction.SetY, 56), new(250, CompileAction.SetY, 57)],
        },
        new() { Name = "WLISTM", Opcode = 214, SpecSize = 67, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(34, CompileAction.PE, 10), new(256, CompileAction.PF, 5), new(257, CompileAction.PF, 15), new(273, CompileAction.PF, 62), new(259, CompileAction.CF, 42), new(28, CompileAction.PF, 25), new(30, CompileAction.PE, 30), new(31, CompileAction.PE, 35), new(249, CompileAction.CUfc, 47), new(253, CompileAction.CUfc, 47), new(264, CompileAction.ChkChr1, 47, "F"), new(252, CompileAction.ChkChr1, 48, "R"), new(258, CompileAction.ChkChr1, 48, "T"), new(260, CompileAction.ChkChr1, 48, "E"), new(254, CompileAction.CUfc, 48), new(265, CompileAction.ChkChr1, 48, "C"), new(272, CompileAction.ChkChr1, 48, "A"), new(16, CompileAction.SetY, 49), new(65, CompileAction.PE, 20), new(64, CompileAction.PF, 55), new(268, CompileAction.SetY, 60), new(269, CompileAction.SetY, 61), new(274, CompileAction.CUfc, 47), new(250, CompileAction.SetY, 64)],
        },
        new() { Name = "DISABLE_ALL", Opcode = 215, SpecSize = 5, IsSpecial = false,
            Options = [new(261, CompileAction.CFAll, 0)],
        },
        new() { Name = "ENABLE_ALL", Opcode = 216, SpecSize = 5, IsSpecial = false,
            Options = [new(261, CompileAction.CFAll, 0)],
        },
        new() { Name = "LOAD_FORM", Opcode = 217, SpecSize = 7, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(270, CompileAction.SetY, 5)],
        },
        new() { Name = "RELEASE_FORM", Opcode = 218, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(263, CompileAction.PE, 5)],
        },
        new() { Name = "ACTIVATE_FORM", Opcode = 219, SpecSize = 6, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(262, CompileAction.SetY, 5)],
        },
        new() { Name = "DATA_GRID", Opcode = 221, SpecSize = 36, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(253, CompileAction.CUfc, 20), new(264, CompileAction.CUfc, 20), new(276, CompileAction.CUfc, 20), new(277, CompileAction.CUfc, 20), new(278, CompileAction.CUfc, 20), new(70, CompileAction.CUfc, 20), new(280, CompileAction.ChkChr1, 20, "E"), new(281, CompileAction.ChkChr1, 20, "R"), new(282, CompileAction.ChkChr1, 20, "T"), new(283, CompileAction.ChkChr1, 20, "F"), new(284, CompileAction.ChkChr1, 20, "G"), new(287, CompileAction.ChkChr1, 20, "U"), new(227, CompileAction.ChkChr1, 20, "A"), new(295, CompileAction.ChkChr1, 20, "I"), new(296, CompileAction.ChkChr1, 20, "L"), new(297, CompileAction.ChkChr1, 20, "V"), new(300, CompileAction.ChkChr1, 20, "Y"), new(301, CompileAction.ChkChr1, 20, "X"), new(98, CompileAction.ChkChr1, 20, "0"), new(231, CompileAction.ChkChr1, 20, "1"), new(319, CompileAction.ChkChr1, 20, "Z"), new(320, CompileAction.ChkChr1, 20, "P"), new(262, CompileAction.PE, 5), new(279, CompileAction.PE, 10), new(64, CompileAction.PF, 15), new(72, CompileAction.PF, 21), new(285, CompileAction.CF, 26), new(105, CompileAction.PF, 31)],
        },
        new() { Name = "PICTURE", Opcode = 222, SpecSize = 40, IsSpecial = false,
            Options = [new(1, CompileAction.CAt, 0), new(77, CompileAction.PF, 10), new(78, CompileAction.PF, 15), new(60, CompileAction.PE, 25), new(27, CompileAction.PE, 30), new(72, CompileAction.CF, 20), new(224, CompileAction.SetY, 35), new(211, CompileAction.SetY, 36), new(212, CompileAction.SetY, 37), new(210, CompileAction.SetY, 38), new(234, CompileAction.SetY, 39)],
            Defaults = [new(CompileAction.ChkNy, 35), new(CompileAction.ChkNy, 36), new(CompileAction.ChkNy, 37), new(CompileAction.ChkNy, 38), new(CompileAction.ChkNy, 39)],
        },
        new() { Name = "SETCBACTIVE", Opcode = 223, SpecSize = 5, IsSpecial = false,
        },
        new() { Name = "SAVE_FORM", Opcode = 224, SpecSize = 10, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(64, CompileAction.PE, 5)],
        },
        new() { Name = "INHERITED", Opcode = 225, SpecSize = 5, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0)],
        },
        new() { Name = "SET_ALL_OBJECTS", Opcode = 226, SpecSize = 20, IsSpecial = false,
            Options = [new(247, CompileAction.PE, 0), new(246, CompileAction.PE, 5), new(275, CompileAction.PF, 10), new(230, CompileAction.PF, 15)],
        },
        new() { Name = "CHECK_SPELLING", Opcode = 227, SpecSize = 20, IsSpecial = false,
            Options = [new(316, CompileAction.PE, 5), new(230, CompileAction.PF, 10), new(275, CompileAction.PF, 15), new(249, CompileAction.SetY, 1)],
        },
        new() { Name = "EDIT_RTM", Opcode = 228, SpecSize = 20, IsSpecial = false,
            Options = [new(0, CompileAction.CFile, 0)],
        },
        new() { Name = "WAIT", Opcode = 229, SpecSize = 20, IsSpecial = false,
        },
        new() { Name = "RANDOMIZE", Opcode = 230, SpecSize = 20, IsSpecial = false,
        },
        new() { Name = "WTREE", Opcode = 231, SpecSize = 67, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(49, CompileAction.PE, 5), new(60, CompileAction.PE, 17), new(262, CompileAction.PF, 23), new(290, CompileAction.PF, 23), new(259, CompileAction.CF, 10), new(316, CompileAction.PE, 29), new(249, CompileAction.CUfc, 15), new(253, CompileAction.ChkChr1, 15, "R"), new(251, CompileAction.ChkChr1, 15, "I")],
        },
        new() { Name = "LISTVIEW", Opcode = 232, SpecSize = 67, IsSpecial = false,
            Options = [new(0, CompileAction.PE, 0), new(49, CompileAction.PE, 5), new(60, CompileAction.PE, 17), new(262, CompileAction.PF, 23), new(290, CompileAction.PF, 23), new(259, CompileAction.CF, 10), new(316, CompileAction.PE, 29), new(249, CompileAction.CUfc, 15), new(253, CompileAction.ChkChr1, 15, "R"), new(251, CompileAction.ChkChr1, 15, "I"), new(156, CompileAction.PE, 35)],
        },
    ];
}